# FileList:
#   Include:
#     - "**/*.feature"
#   Exclude:
#     - "**/*_exclusionary_special.feature"

Style/FeatureName:
  Enabled: true

Style/IndentationWidth:
  Enabled: true
  # Number of spaces for each indentation level.
  Width: 2
