AllCheckers:
  Formatters:
    # Summary does not need to be added here explicitly
    - Progress
    - SimpleText
  Include:
    - "**/*.feature"
  # Exclude:
  #   - "some/excluded/path/*.feature"

Style/FeatureName:
  Enabled: true
  # Allow non-alphanumeric characters, e.g. filename test_thing.feature with text "Feature: (test) thing"
  AllowPunctuation: true
  EnforceTitleCase: false

Style/IndentationWidth:
  Enabled: true
  # Number of spaces for each indentation level.
  Width: 2
