FileList:
  # Array of globs of files to lint.
  Include:
    - "**/*.feature"

Style/FeatureName:
  Enabled: true

Style/IndentationWidth:
  Enabled: true
  # Number of spaces for each indentation level.
  Width: 2
