# AllCheckers:
#   Include:
#     - "**/*.feature"
#   Exclude:
#     - "**/*_exclusionary_special.feature"

Style/FeatureName:
  Enabled: true
  # Allow non-alphanumeric characters, e.g. filename test_thing.feature with text "Feature: (test) thing"
  AllowPunctuation: true
  EnforceTitleCase: false

Style/IndentationWidth:
  Enabled: true
  # Number of spaces for each indentation level.
  Width: 2
